### ISSUE TITLE
Crash of process in case of exception

### ISSUE THREAD

**Issue by osallou** [shelleg/prometheus_libvirt_exporter#1]
In case of an exception while reading libvirt stats, the process crash.
Exception should be caught in main process and "skip" the exception with just a log error instead of exiting with an exception. I faced this issue several times (certainly when getting stats while shutting down a VM or something like that).

    Apr 12 14:48:52 compute10 libvirt_export.sh: Traceback (most recent call last):
    Apr 12 14:48:52 compute10 libvirt_export.sh: File "libvirt_exporter.py", line 191, in <module>
    Apr 12 14:48:52 compute10 libvirt_export.sh: main()
    Apr 12 14:48:52 compute10 libvirt_export.sh: File "libvirt_exporter.py", line 188, in main
    Apr 12 14:48:52 compute10 libvirt_export.sh: scheduler.run()
    Apr 12 14:48:52 compute10 libvirt_export.sh: File "/usr/lib64/python2.7/sched.py", line 117, in run
    Apr 12 14:48:52 compute10 libvirt_export.sh: action(*argument)
    Apr 12 14:48:52 compute10 libvirt_export.sh: File "libvirt_exporter.py", line 172, in job
    Apr 12 14:48:52 compute10 libvirt_export.sh: g_dict = add_metrics(dom, header_mn, g_dict)
    Apr 12 14:48:52 compute10 libvirt_export.sh: File "libvirt_exporter.py", line 95, in add_metrics
    Apr 12 14:48:52 compute10 libvirt_export.sh: stats = dom.getCPUStats(True)
    Apr 12 14:48:52 compute10 libvirt_export.sh: File "/root/venv/lib/python2.7/site-packages/libvirt.py", line 1273, in getCPUStats
    Apr 12 14:48:52 compute10 libvirt_export.sh: if ret is None: raise libvirtError ('virDomainGetCPUStats() failed', dom=self)
    Apr 12 14:48:52 compute10 libvirt_export.sh: libvirt.libvirtError: Domain not found: no domain with matching uuid

**Comment by beylisstan** [comment]
Hey, first of all sorry for long response time.
I was trying reproduce your scenario with spin up and shut down vm's and exporter doesn't fall in described exception.

Successfully connected to qemu:///system
centos6_2
FINISH JOB : 1526553483.81
BEGIN JOB : 1526553488.81
Successfully connected to qemu:///system
No running domains in URI
No running domains in URI

If i am shutting down vm exporter should print out "No running domains in URI" as in example below, may describe more details regarding your scenario and your environment?

**Comment by osallou** [comment]
Unfortunatly i can't reproduce, it occurs sometimes but i don't know exactly
when.
We have an openstack setup with kvm, and sometimes this error occurs

**Comment by osallou** [comment]
Just got a new error on memoryStat this time

    May 24 16:54:48 compute5 libvirt_export.sh: Traceback (most recent call last):
    May 24 16:54:48 compute5 libvirt_export.sh: File "libvirt_exporter.py", line 191, in <module>
    May 24 16:54:48 compute5 libvirt_export.sh: main()
    May 24 16:54:48 compute5 libvirt_export.sh: File "libvirt_exporter.py", line 188, in main
    May 24 16:54:48 compute5 libvirt_export.sh: scheduler.run()
    May 24 16:54:48 compute5 libvirt_export.sh: File "/usr/lib64/python2.7/sched.py", line 117, in run
    May 24 16:54:48 compute5 libvirt_export.sh: action(*argument)
    May 24 16:54:48 compute5 libvirt_export.sh: File "libvirt_exporter.py", line 172, in job
    May 24 16:54:48 compute5 libvirt_export.sh: g_dict = add_metrics(dom, header_mn, g_dict)
    May 24 16:54:48 compute5 libvirt_export.sh: File "libvirt_exporter.py", line 101, in add_metrics
    May 24 16:54:48 compute5 libvirt_export.sh: stats = dom.memoryStats()
    May 24 16:54:48 compute5 libvirt_export.sh: File "/root/venv/lib/python2.7/site-packages/libvirt.py", line 1473, in memoryStats
    May 24 16:54:48 compute5 libvirt_export.sh: if ret is None: raise libvirtError ('virDomainMemoryStats() failed', dom=self)
    May 24 16:54:48 compute5 libvirt_export.sh: libvirt.libvirtError: Timed out during operation: cannot acquire state change lock (held by remoteDispatchDomainCreateWithFlags)
    May 24 16:54:48 compute5 systemd: libvirt_exporter.service: main process exited, code=exited, status=1/FAILURE

Error is *fine* for me, not getting stat because something bad occured, but process should not exit on libvirtError, it should simply log the error and continue its loop

**Comment by beylisstan** [comment]
Try to use code from this fork:
https://github.com/beylisstan/prometheus_libvirt_exporter/blob/master/libvirt_exporter.py

I added some minor fixes with try except statement that's should solve issue.

**Comment by osallou** [comment]
Le sam. 26 mai 2018 à 21:43, beylisstan <notifications@github.com> a écrit :

> Try to use code from this fork:
>
> https://github.com/beylisstan/prometheus_libvirt_exporter/blob/master/libvirt_exporter.py
>
> I added some minor fixes with try except statement that's should solve
> issue.
>
This should indeed prevent exit. Will use your update, but as error occur
infrequently i won't be able to validate it now
..
